version: '2'
services:
  postgres:
    image: postgres:16.3
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./scripts/init-test-db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  aws:
    image: localstack/localstack:3.6.0
    environment:
      - SERVICES=iam
    ports:
      - 4566:4566
      - 8080:8080
