# permissions for end users to view postgresqlserviceusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: postgresqlserviceuser-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: postgresql-controller
    app.kubernetes.io/part-of: postgresql-controller
    app.kubernetes.io/managed-by: kustomize
  name: postgresqlserviceuser-viewer-role
rules:
- apiGroups:
  - postgresql.lunar.tech
  resources:
  - postgresqlserviceusers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - postgresql.lunar.tech
  resources:
  - postgresqlserviceusers/status
  verbs:
  - get
