# permissions for end users to edit postgresqlusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgresqluser-editor-role
rules:
  - apiGroups:
      - postgresql.lunar.tech
    resources:
      - postgresqlusers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - postgresql.lunar.tech
    resources:
      - postgresqlusers/status
    verbs:
      - get
