# permissions for end users to view postgresqlhostcredentials.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgresqlhostcredentials-viewer-role
rules:
- apiGroups:
  - postgresql.lunar.tech
  resources:
  - postgresqlhostcredentials
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - postgresql.lunar.tech
  resources:
  - postgresqlhostcredentials/status
  verbs:
  - get
