# permissions for end users to edit postgresqlhostcredentials.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgresqlhostcredentials-editor-role
rules:
- apiGroups:
  - postgresql.lunar.tech
  resources:
  - postgresqlhostcredentials
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - postgresql.lunar.tech
  resources:
  - postgresqlhostcredentials/status
  verbs:
  - get
