---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
- apiGroups:
  - postgresql.lunar.tech
  resources:
  - customroles
  - postgresqldatabases
  - postgresqlserviceusers
  - postgresqlusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - postgresql.lunar.tech
  resources:
  - customroles/finalizers
  - postgresqlhostcredentials/finalizers
  - postgresqlserviceusers/finalizers
  - postgresqlusers/finalizers
  verbs:
  - update
- apiGroups:
  - postgresql.lunar.tech
  resources:
  - customroles/status
  - postgresqldatabases/status
  - postgresqlhostcredentials/status
  - postgresqlserviceusers/status
  - postgresqlusers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - postgresql.lunar.tech
  resources:
  - postgresqlhostcredentials
  verbs:
  - get
  - list
  - watch
