apiVersion: postgresql.lunar.tech/v1alpha1
kind: PostgreSQLHostCredentials
metadata:
  name: postgresqlhostcredentials-sample
spec:
  host: 127.0.0.1
  user:
    value: postgres
  password:
    value: super-secret-password
  params: sslmode=disable
