apiVersion: postgresql.lunar.tech/v1alpha1
kind: PostgreSQLHostCredentials
metadata:
  namespace: auth
  name: auth
spec:
  host: "postgres.auth.svc.cluster.local"
  user:
    valueFrom:
      secretKeyRef:
        name: "postgres-admin-credentials"
        key: "POSTGRES_USER"
  password:
    valueFrom:
      secretKeyRef:
        name: "postgres-admin-credentials"
        key: "POSTGRES_PASSWORD"
  params: "sslmode=disable"
