name: "CI Workflow"
on: [push, pull_request]

jobs:
  basic-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13.3'
      - uses: jpkrohling/setup-operator-sdk@v1-release
        with:
          operator-sdk-version: v0.11.0

      - name: "Formatting check"
        run: make test/check

      - name: "Compile"
        run: make code/compile

      - name: "Test"
        run: make test/unit
