name: "CI"
on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  basic-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: "1.17.7"

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: "Formatting check"
        run: make fmt/check

      - name: "Compile"
        run: make build

      - name: "Test"
        run: make test/integration
