name: "CI"
on: [push, pull_request]

jobs:
  basic-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v1
        with:
          go-version: "1.17"

      - name: "Formatting check"
        run: make fmt/check

      - name: "Compile"
        run: make build

      - name: "Test"
        run: make test/integration
