name: "Release"
on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v3
        with:
          go-version: "1.19.0"

      - name: Set tag in environment
        run: echo "RELEASE_VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV # extracts the tag name from refs/tags/v1.2.3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: "Build image"
        run: make docker-buildx-build TAG=$RELEASE_VERSION

      - name: "Docker login to Quay.io"
        env:
          DOCKER_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.QUAY_USERNAME }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD quay.io

      - name: "Push image"
        run: make docker-buildx-push TAG=$RELEASE_VERSION
